### PR TITLE
Rainbowize help

### PR DESCRIPTION
**Pull request by SlooowAndFurious**
This fixes issue #3 by displaying a nice rainbow as the help message.
Here is a screenshot

### CODE REVIEW

**Comment by SlooowAndFurious** [comment]
Well, it looks like `clap::App::write_help` does not return the generated help for `--help` and `--version`, I did not read this in the docs, so I guess I should report this. I suggest not accepting this pull request while it is not fixed

**Comment by ur0** [comment]
Thanks for the great PR. I’ll track the upstream issues too.

**Comment by SlooowAndFurious** [comment]
It looks like it won't be fixed before release 3.0.0 according to [issue 808](https://github.com/clap-rs/clap/issues/808), so, a workaround is to use `clap::App::write_long_help` instead. I will do this

**Comment by ur0** [comment]
Unfortunately, clap v3 is still in beta, but #17 resolved this in another way. I'm closing this in favor of the other one, but wish to thank you for your effort anyways!

**Pull request closed without merging**
